// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Privacy by Design Foundation"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the health status of the API service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/vog/issue": {
            "post": {
                "description": "Fetches the result of the disclosure session, compares the disclosed name and date of birth with the person named on the VOG and, when they match, returns a signed IRMA issuance request for the VOG credential (IRMA and SD-JWT VC formats, issued over the IRMA protocol). The credential carries the printed data plus one yes/no attribute per function aspect of the general screening profile (aspect11 ... aspect91). On a mismatch the disclosure is discarded and the user may disclose again with another credential; the uploaded VOG stays available until the session expires.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VOG"
                ],
                "summary": "Verify identity and issue VOG credential",
                "parameters": [
                    {
                        "description": "Session from /vog/upload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.IssuanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "the disclosed identity does not match the VOG, or the disclosure proof is invalid",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "unknown or expired session",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "the disclosure session has not finished (or was not started)",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "the IRMA server could not be reached",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vog/start-disclosure": {
            "post": {
                "description": "Starts a Yivi disclosure session in which the holder proves their identity with one of four credentials: BRP personal data (gemeente.personalData), passport, ID card or driving licence. The Yivi app lets the user pick. The response is the IRMA session package that yivi-frontend consumes directly (use it as the response of the ` + "`" + `session.start` + "`" + ` request with the default mapping and ` + "`" + `result: false` + "`" + `). The requestor token is kept server side.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VOG"
                ],
                "summary": "Start identity disclosure",
                "parameters": [
                    {
                        "description": "Session from /vog/upload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisclosureSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "unknown or expired session",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "the IRMA server did not accept the session",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vog/upload": {
            "post": {
                "description": "Accepts a VOG PDF (multipart form field \"file\"), checks its authenticity and integrity with the GAAV validation service of the Justitiële Informatiedienst (https://validatie.nl) and reads the printed data (name, date of birth, purpose and screening profile codes). On success a session is created that must be used to disclose the holder's identity and to obtain the credential. The session expires after one hour.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VOG"
                ],
                "summary": "Upload and validate a VOG",
                "parameters": [
                    {
                        "type": "file",
                        "description": "The VOG PDF as received from Justis",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "file missing, not a PDF or not a VOG",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "file too large",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "the validation service rejected the document (tampered, unknown or invalid signature)",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "the validation service is unavailable; the backend already retried the call, the client may try again later",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DisclosureSessionResponse": {
            "type": "object",
            "properties": {
                "frontendRequest": {
                    "description": "Frontend session request (pairing options) as produced by the IRMA server",
                    "type": "object"
                },
                "sessionPtr": {
                    "$ref": "#/definitions/models.SessionPointer"
                }
            }
        },
        "models.DocumentInfo": {
            "type": "object",
            "properties": {
                "country_of_birth": {
                    "type": "string",
                    "example": "Nederland"
                },
                "date_of_birth": {
                    "description": "Date of birth, YYYY-MM-DD",
                    "type": "string",
                    "example": "1991-05-14"
                },
                "given_names": {
                    "type": "string",
                    "example": "Jan Willem"
                },
                "issue_date": {
                    "description": "Issue date, YYYY-MM-DD",
                    "type": "string",
                    "example": "2026-03-25"
                },
                "place_of_birth": {
                    "type": "string",
                    "example": "Barneveld"
                },
                "prefix": {
                    "type": "string",
                    "example": "van"
                },
                "profile_codes": {
                    "description": "Screening profile codes as printed on the VOG",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "84",
                        "85"
                    ]
                },
                "profiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProfileInfo"
                    }
                },
                "purpose": {
                    "description": "The function or purpose the VOG was requested for",
                    "type": "string",
                    "example": "Vrijwilliger bij Sportvereniging"
                },
                "reference_number": {
                    "type": "string",
                    "example": "9999012026032500922"
                },
                "surname": {
                    "type": "string",
                    "example": "Jansen"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Stable machine readable error key, e.g. \"error:validation-failed\"",
                    "type": "string",
                    "example": "error:validation-failed"
                },
                "identity": {
                    "description": "Identity comparison outcome when the error concerns the identity match",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.IdentityMatchInfo"
                        }
                    ]
                },
                "message": {
                    "description": "Human readable explanation (English)",
                    "type": "string",
                    "example": "the document was rejected by the validation service"
                },
                "validation": {
                    "description": "Validation outcome when the error concerns the GAAV validation",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ValidationInfo"
                        }
                    ]
                }
            }
        },
        "models.HealthResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "description": "True if the service is healthy",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.IdentityMatchInfo": {
            "type": "object",
            "properties": {
                "date_of_birth_match": {
                    "type": "boolean",
                    "example": true
                },
                "given_names_match": {
                    "type": "boolean",
                    "example": true
                },
                "matched": {
                    "type": "boolean",
                    "example": true
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "surname differs"
                    ]
                },
                "source": {
                    "description": "Which credential the identity came from: brp, passport, id_card or driving_licence",
                    "type": "string",
                    "example": "passport"
                },
                "surname_match": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.IssuanceResponse": {
            "type": "object",
            "properties": {
                "identity": {
                    "description": "Outcome of the identity comparison that authorised the issuance",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.IdentityMatchInfo"
                        }
                    ]
                },
                "irma_server_url": {
                    "description": "URL of the IRMA server for credential issuance",
                    "type": "string",
                    "example": "https://irma.example.com"
                },
                "jwt": {
                    "description": "Signed JWT containing the IRMA issuance request",
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "models.ProfileInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Two digit code as printed on the VOG",
                    "type": "string",
                    "example": "84"
                },
                "description": {
                    "description": "Description (Dutch)",
                    "type": "string",
                    "example": "Belast zijn met de zorg voor minderjarigen"
                },
                "description_en": {
                    "description": "Description (English)",
                    "type": "string",
                    "example": "Being responsible for the care of minors"
                },
                "risk_area": {
                    "description": "Risk area (Dutch)",
                    "type": "string",
                    "example": "Personen"
                }
            }
        },
        "models.SessionPointer": {
            "type": "object",
            "properties": {
                "irmaqr": {
                    "description": "Session type",
                    "type": "string",
                    "example": "disclosing"
                },
                "u": {
                    "description": "Session URL on the IRMA server",
                    "type": "string",
                    "example": "https://irma.example.com/irma/session/abc123"
                }
            }
        },
        "models.SessionRequest": {
            "type": "object",
            "properties": {
                "session_id": {
                    "description": "Session identifier from /vog/upload",
                    "type": "string",
                    "example": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
                }
            }
        },
        "models.UploadResponse": {
            "type": "object",
            "properties": {
                "document": {
                    "$ref": "#/definitions/models.DocumentInfo"
                },
                "session_id": {
                    "description": "Session identifier to use in the follow-up requests (32 hex characters)",
                    "type": "string",
                    "example": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
                },
                "validation": {
                    "$ref": "#/definitions/models.ValidationInfo"
                }
            }
        },
        "models.ValidationInfo": {
            "type": "object",
            "properties": {
                "authentic": {
                    "description": "True when the document is authentic and integral",
                    "type": "boolean",
                    "example": true
                },
                "code": {
                    "description": "Raw response code of https://validatie.nl (0 = authentic and integral)",
                    "type": "integer",
                    "example": 0
                },
                "description": {
                    "description": "Dutch description from the GAAV API specification",
                    "type": "string",
                    "example": "Document is authentiek en integer."
                },
                "key": {
                    "description": "Stable key for the code: authentic, known_not_integral, unknown_document, validation_unavailable, provenance_error, signature_server_error, invalid_signature, provenance_store_error",
                    "type": "string",
                    "example": "authentic"
                },
                "retryable": {
                    "description": "True when the failure is on the side of the validation service and retrying may help",
                    "type": "boolean",
                    "example": false
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Go VOG Issuer API",
	Description:      "API for validating a Verklaring Omtrent het Gedrag (VOG, Dutch certificate of conduct) and issuing it as a privacy-preserving Yivi credential.\nThe service validates the uploaded VOG PDF with the GAAV validation service of the Justitiële Informatiedienst (https://validatie.nl), reads the printed data, lets the holder prove their identity with a BRP, passport, ID card or driving licence credential in the Yivi app, checks that this identity matches the person named on the VOG and then issues the VOG credential (IRMA and SD-JWT VC formats) over the IRMA protocol.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
